Repository openshift/multus-admission-controller, pull requests merged in 2019-07, with the labels that each got.

#7 Reload certs
  .travis.yml
  cmd/webhook/main.go
  pkg/webhook/tlsutils.go
Labels: lgtm, size/L

#8 Fix ListenAndServeTLS to use GetCertificate correctly
  cmd/webhook/main.go
Labels: lgtm, size/XS

#9 build.sh: remove no_openssl
  build.sh
Labels: approved, lgtm, size/XS
