Repository openshift/multus-admission-controller, pull requests merged in 2019-11, with the labels that each got.

#14 Initialize metrics
  OWNERS
  pkg/controller/controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/S

#15 Renamed metrics name as per telemetry requirements
  README.md
  cmd/webhook/main.go
  docs/metrics.md
  pkg/controller/controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/M

#16 Bug 1769435 Add minimum required field check in CNI json validataion
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#17 Fixed bug with wrong counts.
  pkg/controller/controller.go
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm, size/L
